title: React Native Frame Capture
description: Reliable screen capture for React Native Android
theme: jekyll-theme-cayman
show_downloads: true
github:
  repository_url: https://github.com/nasyx-rakeeb/react-native-frame-capture
  zip_url: https://github.com/nasyx-rakeeb/react-native-frame-capture/zipball/main
  tar_url: https://github.com/nasyx-rakeeb/react-native-frame-capture/tarball/main
